# Default server configuration.
host: localhost
port: 3000
# postgres:
#   database_name: tvc12_news
#   username: admin
#   password: admin
postgres:
  host: $HOST_POSTGRES
  database_name: $DATABASE_NAME
  username: $USERNAME
  password: $PASSWORD
  port: $PORT_DATABASE
  use_ssl: $USE_SSL
jwt_secret: "iyXrOiTnHCWqAKUPsOvLxoWmrF6ShxB9"
