# Production-only server configuration
debug: false
host: $HOST_TVC
port: $PORT
postgres:
  database_name: $DATABASE_NAME
  username: $USERNAME
  password: $PASSWORD
  port: $PORT_DATABASE
  use_ssl: $USE_SSL
